// comment/react/app.jsx
import { useRef, useEffect, useState, useCallback } from 'react'
import { createRoot } from 'react-dom/client'

const App = () => {
  const mounted = useRef(false)
  const [ intervalId, setIntervalId ] = useState(null)
  const [ now, setNow ] = useState(null)
  const [ date, setDate ] = useState(null)
  const [ time, setTime ] = useState(null)
  
  const step = useCallback(() => {
    setNow((new Date()).toISOString())
  }, [])
  
  useEffect(() => {
    if (!mounted.current) {
      mounted.current = true
      setIntervalId(setInterval(step, 1000))
    }
    
    return () => {
      clearIntervall(intervalId)
    }
  }, [ mounted ])
  
  useEffect(() => {
    if (now) {
      const [ _date, _time ] = now.split('T')
      
      setDate(_date)
      setTime(_time.slice(0, 8))
    }
  }, [ now ])
  
  return (date && time) ? (<h1>{date} / {time}</h1>) : null
}

const container = document.getElementById('root')
const root = createRoot(container)
root.render(<App />)

// comment/vue/App.vue
<script setup>
  import { onMounted, onUnmounted, ref, watchEffect } from 'vue'
  
  const intervalId = ref(null)
  const now = ref(null)
  const date = ref(null)
  const time = ref(null)

  onMounted(() => {
    intervalId.value = setInterval(step, 1000)
  })

  onUnmounted(() => {
    clearInterval(intervalId)
  })

  watchEffect(() => {
    if (now.value) {
      const [ _date, _time ] = now.value.split('T')

      date.value = _date
      time.value = _time.slice(0, 8)
    }
  })

  function step() {
    now.value = (new Date()).toISOString()
  }
</script>

<template>
  <h1 v-if="date && time">{{date}} / {{time}}</h1>
</template>

<style>
  body {
    text-align: center;
    font-family: sans-serif;
  }
</style>
